### ISSUE TITLE
Allow specifying encoding of variables

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#269]
**Is your feature request related to a problem? Please describe.**
xcube gen sets the variable encoding by default to float32 (except for the coordinate variables, there for lat, lon (+bnds)  its float64 and time (+bnds) is datetime64.  
However, not always float32 is needed for certain variables

**Describe the solution you'd like**
to_zarr allows to specify encodings and it would be great if one could specify those within the configuration file by : 

```
output_writer_params:
  encoding:
    chl_c2rcc:
      scale_factor: 0.003662221137119663
      add_offset: 0.0
      dtype: uint16
      _FillValue: 65535
```
