### ISSUE TITLE
Allow for variables computed on-the-fly

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#272]
**Is your feature request related to a problem? Please describe.**

We'd like to add computed variables to data cubes published by `xcube serve`.
We already support computed cubes in `xcube serve` configurations, but that creates entirely new cubes (e.g. resampled in time). We now need to augment existing cubes by newly computed variables.  

**Describe the solution you'd like**

Add a section `Augmentation` into dataset descriptor, e.g.:

```yaml
Datasets:
  - Identifier: abc
    ...
    Augmentation:
      Path: compute_new_vars.py
```

The `Augmentation` entry may later be extended to also support variables computed from simple expressions:

```yaml
    Augmentation:
      Variables: 
          - Name: conc_chl_g
            Expression: conc_chl / 1000
            Attributes:
               - units: "g / m^3" 
          - ...          
```
