### ISSUE TITLE
Allow configuration of AWS S3 credentials

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#296]
What is urgently needed:

```yaml

Datasets:
  - Identifier: ...
    FileSystem: obs
    Endpoint: "http://obs.eu-de.otc.t-systems.com"
    Path: "dcs4cop-obs-02/OLCI-SNS-RAW-CUBE-2.zarr"
    Region: "eu-de"
    # NEW:
    AccessKeyId: ...
    SecretAccessKey: ...
```
