### ISSUE TITLE
no effect of "--styles" parameter in "xcube serve"

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#379]
**Describe the bug**
When using `xcube serve` with the `--styles`  parameter it does not have desired effect of adjusting the value ranges or using the specified colormap. It just uses the default settings. 

**To Reproduce**
1. Start xcube serve with the example cube in /xcube/examples/serve/demo/cube-1-250-250.zarr and the styles parameter: 
`$ xcube serve examples/serve/demo/cube-1-250-250.zarr --styles 'conc_chl=(0.,20.,"plasma")' -v`
By the way, when omitting the quotation marks around `conc_chl=(0.,24.,"plasma")` an error appears. 
2. start xcube viewer: 
![image](https://user-images.githubusercontent.com/23457217/100219775-b3f69600-2f16-11eb-9eb0-23250fb41724.png)
3. create a config.yml file with 
```
Datasets:
  - Identifier: local
    Title: "Example Cube"
    FileSystem: local
    Path: "examples/serve/demo/cube-1-250-250.zarr"
    Style: default

Styles:
  - Identifier: default
    ColorMappings:
      conc_chl:
        ColorBar: "plasma"
        ValueRange: [0., 24.]
```
4. start the server with `$ xcube serve -c config.yml -v`
5. start xcube viewer: 
![image](https://user-images.githubusercontent.com/23457217/100219869-d8eb0900-2f16-11eb-9d26-d1ae13c143e5.png)

When starting xcube serve with the specified styles in the config.yml they are applied as expected.
