### ISSUE TITLE
Allow ServiceConfig to load from env

### ISSUE THREAD

**Issue by dzelge** [dcs4cop/xcube#454]
**Is your feature request related to a problem? Please describe.**

Services are configured using environment variables when running xcube on the EDC infrastructure. When running the cube generator, one needs to collect those env variables and pass their values into  the ServiceConfig.from_dict-method as dictionary to configure the service's endpoint_url, client_id, as well as client_secret. 

**Describe the solution you'd like**

Add a `from_env` method to the `class ServiceConfig` that allows loading service configurations from env variables. 

**Describe alternatives you've considered**

None

**Comment by forman** [comment]
Instead of adding a new method, referenced env vars should be used to interpolate certain values in the store configuration YAML file, for example

```yaml
sentinelhub_eu:
  title: SENTINEL Hub (Central Europe)
  description: Datasets from the SENTINEL Hub API deployment in Central Europe
  store_id: sentinelhub
  store_params:
    api_url: https://services.sentinel-hub.com
    client_id: "${SH_CLIENT_ID}"
    client_secret: "${SH_CLIENT_SECRET}"

cop_services_data:
  title: Datasets from Copernicus Services
  store_id: s3
  store_params:
    bucket_name: "${COP_SERVICES_DATA_BUCKET}"
    aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
    aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
```
