### ISSUE TITLE
Masking certain variables during xcube gen process

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#462]
**Is your feature request related to a problem? Please describe.**
Usually a user is interested only in a particular region, which is not a bounding box but e.g. a selection of lakes. Currently we can only create xcube datasets which show all data in a certain bounding box. It would be great, if in the cube generation process one could define which variables should be masked it they are not within a certain Multipopligon or shapefile. 

Example: A user only wants 3 Lakes of the Mecklenburg Lake Plateau for chlorophyll, but wants to be able see the RGB image in xcube-viewer for a larger bounding box. This would mean, only chlorophyll is masked with the help of e.g. a shape file and the bands needed for RGB are kept in their whole extent. 

**Describe the solution you'd like**
I would like to be able to provide in the cube gen config a list of variables together with a path to geometry to indicate which variables should be masked. 

**Describe alternatives you've considered**
Currently we do this masking on the fly through the xcube-viewer configuration. The main problem about this solution is, that it is slow and the user experience is therefore not too great. 

**Additional context**

The code for masking certain variables on the fly used by xcube-viewer is like below: 

```
import geopandas as gpd
import xarray as xr
import salem
import yaml


def mask_by_geometry(ds, vars_for_masking, details_for_masking, geometry):
    region = gpd.read_file(geometry)
    with open(details_for_masking) as f:
        details = yaml.load(f, Loader=yaml.FullLoader)
    masked_vars = {}
    for var in vars_for_masking:
        var_masked = ds[var].salem.roi(shape=region)
        if var in details.keys():
            var_masked = var_masked.rename(details[var]['var_name'])
            attrs_dict = details[var].copy()
            attrs_dict.pop('var_name', None)
            var_masked = var_masked.assign_attrs(attrs_dict)
            masked_vars[details[var]['var_name']] = var_masked
        else:
            var_masked = var_masked.rename(f'{var}_masked')
            masked_vars[f'{var}_masked'] = var_masked
    return xr.Dataset(masked_vars)
```

and the details for masking are held in a yml file like this, providing information about new metadata for a masked variable. This part does not have to be included into the masking during cube gen process, but could be considered. 

```
chl_c2rcc:
  var_name: "Klorofyll-a"
  long_name: "Klorofyll-a"
  original_name: "chl_c2rcc"
  units: "µg/L"

immersed_cyanobacteria:
  var_name: "Indikator-Cyanobakterier"
  long_name: "Indikator – Cyanobakterier"
  original_name: "immersed_cyanobacteria"
```

**Comment by forman** [comment]
> Currently we do this masking on the fly through the xcube-viewer configuration. 

The xcube-viewer currently doesn't know anything about "masks".

> The code for masking certain variables on the fly used by xcube-viewer is like below

This is Python code, but xcube-viewer is TypeScript. To which code do you refer to?

> and the details for masking are held in a yml file like this, providing information about new metadata for a masked variable. 

Where does this come from? Which mask information are you referring to?

**Comment by AliceBalfanz** [comment]
Apologies, I meant the xcube server configuration, which gives the possibility to add an augmentation to a dataset: 
```
    Augmentation:    
              Path: "mask_by_geometry.py"
              Function: "mask_by_geometry"
              InputParameters:
                            vars_for_masking: ["chl_c2rcc", "immersed_cyanobacteria"]
                            details_for_masking: "details_for_masking_syvab.yml"
                            geometry: "../../../data/places/Syvvab_Himmerfjarden_wgs84.shp"
```
