### ISSUE TITLE
xcube serve overwrites Colormap and Valuerange given in Metadata

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#550]
**Describe the bug**
When saving the corresponding Color ramp and valid value range for a variable it is not used for displaying the variable accordingly in the viewer. xcube serve ignores this data and uses default value ranges from 0 to 1, as well as colormap 'viridis'.

I tried different metadata for MCI: 

    mci.attrs['colorBarMin'] = 0.
    mci.attrs['colorBarMax'] = 0.02
    mci.attrs['colorBarName'] = 'plasma'

and (following the pattern Styles are defined for datasets with xcube serve): 

    mci.attrs['ValueRange'] = [0, 0.02]
    mci.attrs['ColorBar'] = 'plasma'

You can see the Result for variable MCI when starting a local server with the below configuration and view it in xcube viewer. 

server configuration: 
```
DatasetAttribution:
  - "© by Brockmann Consult GmbH 2021"
  - "© by  ESA Data Cube Facility Service (DCFS) project"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: edc
    StoreId: s3
    StoreParams:
      root: eurodatacube-scratch/public
      max_depth: 1
      storage_options:
        anon: true
        # client_kwargs:
        #  endpoint_url: https://s3.eu-central-1.amazonaws.com
    Datasets:
      - Identifier: "*.zarr"

```
The metadata of MCI shown in viewer: 

![image](https://user-images.githubusercontent.com/23457217/137323197-26796f5a-14f5-49c7-b950-8b9a9ec3c32d.png)

and
 
![image](https://user-images.githubusercontent.com/23457217/137324012-fc072784-ec7b-41dc-98b6-160bf09985e9.png)
