### ISSUE TITLE
Only last configured Identifier is published via xcube serve for StoreID: s3 

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#576]
xcube server only serves last Identifier when configuring several datasets within a DataStore Identifier. 

I would expect to see all datacube matching any pattern listed as an Identifier. I also tested without wildcards, which does not change the behavior.  

```
DatasetAttribution:
  - "© by Brockmann Consult GmbH 2020, contains modified Copernicus Data 2019, processed by ESA"
  - "© by EU H2020 CyanoAlert project"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: Sweden
    StoreId: s3
    StoreParams:
      root: water-services/Sweden
      max_depth: 1
      storage_options:
        anon: false
    Datasets:
      - Identifier: "l2c*Sweden*.zarr"
        Style: "default"
      - Identifier: "ws*Sweden*.zarr"
        Style: "default"
```
When adding a new DatStore, with a path to a different bucket, the behaviour persists. Of each DataStore the last configured Dataset Identifier is visible in xcube viewer. 

```
DatasetAttribution:
  - "© by Brockmann Consult GmbH 2020, contains modified Copernicus Data 2019, processed by ESA"
  - "© by EU H2020 CyanoAlert project"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: Sweden
    StoreId: s3
    StoreParams:
      root: water-services/Sweden
      max_depth: 1
      storage_options:
        anon: false
    Datasets:
      - Identifier: "l2c*Sweden*.zarr"
        Style: "default"
      - Identifier: "ws*Sweden*.zarr"
        Style: "default"

DataStores:
  - Identifier: Germany
    StoreId: s3
    StoreParams:
      root: water-services/Germany
      max_depth: 1
      storage_options:
        anon: false
    Datasets:
      - Identifier: "l2c*Germany*.zarr"
        Style: "default"
      - Identifier: "ws*.zarr"
        Style: "default"
```
Server output:

![image](https://user-images.githubusercontent.com/23457217/146211065-9fa488cd-cac8-44a3-91fe-674f8bf7bfd9.png)
