### ISSUE TITLE
xcube server cannot serve nested datasets

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#579]
**Describe the bug**
I have a s3 cloud bucket, where user can store their cubes. These cubes are served by xcube server in order to be visualised with xcube viewer. I don't know how many cubes each user has or who the user are. The bucket structure is: `s3://<bucket>/cubes/<user_name>/*.zarr` 

therefore my configuration of the server looks like this: 

```
DataStores:
  - Identifier: <precise_identifyer>
    StoreId: s3
    StoreParams:
      root: <bucket>/cubes
      max_depth: 3
      storage_options:
        anon: false # I have a .aws file, which 
    Datasets:
      - Identifier: "*.zarr"
        Style: "default"
```

The viewer launches without problem, but does not show the data layer of first data cube of the list. It is the correct location within the bucket though, shown by the id in the info panel. I know where the data of the cube is, therefore create a time series for a point where I know data should be. This leads to a `Cannot reach server` message:

![image](https://user-images.githubusercontent.com/23457217/149083807-74dfb429-5264-4490-802e-33fdd6794ce9.png)

![image](https://user-images.githubusercontent.com/23457217/149083950-b98eecec-9b13-42c3-8f02-1c8dfdae2828.png)

the server logs don't show any errors: 
```
(xcube) alicja@alicja:~/Desktop/projects/service-cyanoalert$ xcube serve -c /home/alicja/Desktop/projects/service-cyanoalert/bigfe/1_development/xcube-viewer-app/stage/api/server-config_for_testing.yml -v 
xcube Server: WMTS, catalogue, data access, tile, feature, time-series services for xarray-enabled data cubes, version 0.9.3.dev0
[I 220112 08:33:31 service:239] configuration file '/home/alicja/Desktop/projects/service-cyanoalert/bigfe/1_development/xcube-viewer-app/stage/api/server-config_for_testing.yml' successfully loaded
[I 220112 08:33:31 service:168] service running, listening on localhost:8080, try http://localhost:8080/datasets
[I 220112 08:33:31 service:169] press CTRL+C to stop service
[I 220112 08:34:03 perf:79] get granted scopes: took 0.03ms
[I 220112 08:34:03 context:283] scanning store 'bigfe'
[I 220112 08:34:03 credentials:1224] Found credentials in shared credentials file: ~/.aws/credentials
```

For testing reasons I do know the user prefix in the bucket, and if I test them separately they work as expected: 

```
DataStores:
  - Identifier: <precise_identifyer>
    StoreId: s3
    StoreParams:
      root: <bucket>/cubes/<user_name>
      max_depth: 3
      storage_options:
        anon: false # I have a .aws file, which 
    Datasets:
      - Identifier: "*.zarr"
        Style: "default"
```

![image](https://user-images.githubusercontent.com/23457217/149084460-b1e3f21c-4e8b-435f-88c7-427cd2d54554.png)
