### ISSUE TITLE
xcube gen2 DataStore configuration to understand env var references

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#580]
I want to configure a data store which contains input files to be used xcube gen2 service generator. The data is located in an s3 bucket which is protected, so my configuration looks like the following:

```
my_data:
  title: "My Data for xcube gen2"
  store_id: s3
  store_params:
    root: "<bucket-path>"
    storage_options:
      key: "${MY_ACCESS_KEY_ID}"
      secret: "${MY_SECRET_ACCESS_KEY}"
```
This leads into an "Access denied" issue. When I put the credentials straight into the configuration, it works as expected. I wish for the same behavior when using env var references. :)
