### ISSUE TITLE
xcube serve too strict wrt spatial x,y resolutions

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#590]
**Is your feature request related to a problem? Please describe.**

`xcube serve` rejects datasets whose x and y resolutions are different by the default epsilon of `math.isclose()`. This is too strict.

**Describe the solution you'd like**

I such cases use datasets anyway and post warning.

**Comment by AliceBalfanz** [comment]
The xcube viewer crashes, when a cube has different x and y, with older versions we got a warning:
`[W 220331 10:55:03 catalogue:120] skipping dataset avl~pont-us/test1.zarr: spatial resolutions are different in x, y: 0.000199795 and 0.00020218`

now the logs look the folowing: 
```
(xcube) alicja@alicja:~/Desktop/projects/xcube$ xcube serve -c /home/alicja/Desktop/projects/service-xcube-viewer-apps/avl/dev/api/server-config.yml -v --traceperf
xcube Server: WMTS, catalogue, data access, tile, feature, time-series services for xarray-enabled data cubes, version 0.11.0.dev0
[I 220331 14:49:53 service:244] configuration file '/home/alicja/Desktop/projects/service-xcube-viewer-apps/avl/dev/api/server-config.yml' successfully loaded
[I 220331 14:49:53 service:174] service running, listening on localhost:8080, try http://localhost:8080/datasets
[I 220331 14:49:53 service:175] press CTRL+C to stop service
[I 220331 14:50:36 perf:79] get granted scopes: took 0.04ms
[I 220331 14:50:36 context:429] scanning store 'avl'
[I 220331 14:50:36 credentials:1224] Found credentials in shared credentials file: ~/.aws/credentials
[I 220331 14:50:38 perf:79] opened dataset 'avl~pont-us/test1.zarr' from data store 'avl': took 541.84ms
[I 220331 14:50:38 perf:79] opened dataset 'avl~pont-us/test2.zarr' from data store 'avl': took 414.58ms
```

but the xcube viewer shows no map at all: 
![image](https://user-images.githubusercontent.com/23457217/161069969-38431b57-ee8a-4578-a575-e018defa7bc8.png)


To reproduce: 

Start local server with 

```yaml
DataStores:
  - Identifier: avl
    StoreId: s3
    StoreParams:
      root: agriculture-vlab-user
      max_depth: 2
      storage_options:
        anon: false
    Datasets:
      - Path: "*.zarr"
        Style: "default"
```

and launch a local viewer.
