### ISSUE TITLE
Data resource "OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr" does not exist in store

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#603]
**Describe the bug**
I am requesting  a dataset of an s3 store to xcube gen2 service and I get an Error:  `click.exceptions.ClickException: Data resource "OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr" does not exist in store`.

This was working a couple weeks ago. 

**To Reproduce**

You need to have Creodias credentials exported in your testing environment and a .aws file which is allowing you to write into our eurodatacube-scratch bucket.
1. Create a local store config with: 
```
cop_services_cmems:
  title: "CMEMS Copernicus Datasets on S3"
  store_id: s3
  store_params:
    root: "EODATA/CMEMS/NRT"
    max_depth: 5
    storage_options:
      key: "${CREODIAS_ACCESS_KEY_ID}"
      secret: "${CREODIAS_SECRET_ACCESS_KEY}"
      client_kwargs:
        endpoint_url: "https://s3.cloudferro.com"
        region_name: "US"
```

2. Create a config file with the request-config: 
```
cube_config:
  bbox:
  - 30
  - 41
  - 40
  - 45
  crs: WGS84
  spatial_res: 0.01407
  time_period: 1D
  time_range:
  - '2019-06-01'
  - '2019-07-01'
  variable_names:
  - CHL
input_configs:
- data_id: OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr
  open_params: {}
  store_id: '@cop_services_cmems'
output_config:
  data_id: cop-services-OC-BS_CHL.zarr
  replace: true
  store_id: s3
  store_params:
    root: eurodatacube-scratch
```

3. xcube --traceback gen2 request-cop-services-OC-BS_CHL.yml --stores redc-stores-config.yml -v

```
Cube generator request loaded from request_cube_configs/request-cop-services-OC-BS_CHL.yml.
Generating cube - ...
Generating cube - 0.0%: reading cube - ...
Generating cube - 0.0%: reading cube - done.
Generating cube - error!
{
  "status": "error",
  "message": "Data resource \"OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr\" does not exist in store",
  "traceback": [
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/cli/gen2.py\", line 141, in gen2\n    result = generator.generate_cube(request).to_dict()\n",
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/generator.py\", line 196, in generate_cube\n    result = self._generate_cube(request)\n",
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/generator.py\", line 113, in _generate_cube\n    return self.__generate_cube(request)\n",
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/generator.py\", line 174, in __generate_cube\n    t_cube = opener.open_cube(input_config)\n",
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/opener.py\", line 71, in open_cube\n    opener_id = self._get_opener_id(\n",
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/opener.py\", line 116, in _get_opener_id\n    data_type_names = store.get_data_types_for_data(\n",
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/store/fs/store.py\", line 190, in get_data_types_for_data\n    self._assert_valid_data_id(data_id)\n",
    "  File \"/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/store/fs/store.py\", line 445, in _assert_valid_data_id\n    raise DataStoreError(f'Data resource \"{data_id}\"'\n"
  ],
  "status_code": 500,
  "versions": {
    "xcube": "0.9.3.dev0",
    "xcube_cci": "0.9.4.dev0",
    "xcube_cds": "0.9.2.dev0",
    "xcube_sh": "0.9.4.dev0",
    "affine": "2.3.0",
    "click": "8.0.3",
    "cmocean": "2.0",
    "dask": "2022.01.1",
    "distributed": "2022.01.1",
    "fiona": "1.8.20",
    "fsspec": "2022.01.0",
    "geopandas": "0.10.2",
    "jdcal": "1.4.1",
    "jsonschema": "4.4.0",
    "numba": "0.55.0",
    "numpy": "1.21.5",
    "pandas": "1.4.0",
    "pyproj": "3.3.0",
    "rasterio": "1.2.10",
    "requests": "2.27.1",
    "s3fs": "2022.01.0",
    "scipy": "1.7.3",
    "setuptools": "59.8.0",
    "shapely": "1.8.0",
    "tornado": "6.1",
    "urllib3": "1.26.8",
    "xarray": "0.21.1",
    "zarr": "2.10.3"
  }
Error: Data resource "OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr" does not exist in store
Traceback (most recent call last):
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/cli/gen2.py", line 141, in gen2
    result = generator.generate_cube(request).to_dict()
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/generator.py", line 196, in generate_cube
    result = self._generate_cube(request)
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/generator.py", line 113, in _generate_cube
    return self.__generate_cube(request)
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/generator.py", line 174, in __generate_cube
    t_cube = opener.open_cube(input_config)
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/opener.py", line 71, in open_cube
    opener_id = self._get_opener_id(
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/gen2/local/opener.py", line 116, in _get_opener_id
    data_type_names = store.get_data_types_for_data(
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/store/fs/store.py", line 190, in get_data_types_for_data
    self._assert_valid_data_id(data_id)
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/core/store/fs/store.py", line 445, in _assert_valid_data_id
    raise DataStoreError(f'Data resource "{data_id}"'
xcube.core.store.error.DataStoreError: Data resource "OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr" does not exist in store

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/cli/main.py", line 66, in main
    exit_code = cli.main(args=args, obj=ctx_obj, standalone_mode=False)
  File "/home/alicja/miniconda3/envs/xcube-dev_local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/alicja/miniconda3/envs/xcube-dev_local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alicja/miniconda3/envs/xcube-dev_local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alicja/miniconda3/envs/xcube-dev_local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/alicja/Desktop/projects/xcube-dev_local/xcube/cli/gen2.py", line 174, in gen2
    raise click_error from error
click.exceptions.ClickException: Data resource "OCEANCOLOUR_BS_CHL_L4_NRT_OBSERVATIONS_009_045.zarr" does not exist in store
```

**Expected behavior**
I tested this a couple weeks ago and was not a problem at all. maybe related to https://github.com/dcs4cop/xcube/issues/586
