### ISSUE TITLE
xucbe server DataStores configuration wont see any multi-level datasets

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#653]
**Describe the bug**

The `xcube serve` `DataStores` configuration doesn't see any multi-level datasets. In fact, the code currently just scans for resources of data type `dataset` and explicitly excludes `mldataset`. 

**To Reproduce**

Put following section in to `examples/serve/demo/config.yml` and run `xcube serve`. 

```yaml
DataStores:
  - Identifier: "xcube-eea"
    StoreId: "s3"
    StoreParams:
      root: "eurodatacube-test/xcube-eea"
      storage_options:
        anon: false
    Datasets:
      - Path: "hr_mr_tprod-iberia-10m-2017-2020.levels"
```

**Expected behavior**

Must scan both `dataset` and `mldatasets`. The latter are even more important.

**Screenshots**

xcube/webapi/context.py:

![image](https://user-images.githubusercontent.com/206773/159120678-cc2c6314-9e5e-4191-9217-52dc8fa26286.png)
