### ISSUE TITLE
xcube Server publishes level datasets of multi-level dataset

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#658]
**Describe the bug**

If xcube Server is configured to serve an "s3" data store that contains a multi-level dataset (say `test.levels`) it will not only publish the multi-level dataset but also its level datasets (`test.levels/0.zarr`, `test.levels/1.zarr` , ...).

**To Reproduce**

`xcube serve` config:

```yaml
DataStores:
  - Identifier: test
    StoreId: s3
    StoreParams:
       root: ...
       max_depth: 2
       storage_options:
         anon: ...
         ...
    Datasets:
      - Path: *.levels
      - Path: *.zarr
``` 

**Expected behavior**

Level datasets of a multilevel-dataset should not be published unless explicitly configured.
