### ISSUE TITLE
xcube gen2 failing for antimeridian region of interest

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#682]
**Describe the bug**
xcube gen2 fails to build cubes which areas cross the antimeridian. To reproduce, please use the below request. 

the below  xcube request config is used and xcube gen2 triggered with the following the cli command: 

`xcube --traceback gen2 request_cube_configs/request-sh-antimeridian_S2L2A_B04_B05.yml --service request_store_configs/edc-service-stage-config.yml -v`

```
cube_config:
  bbox:
  - 179.69
  - 65.04
  - -177.76
  - 66.72
  chunks:
    lat: 512
    lon: 512
    time: 1
  crs: WGS84
  spatial_res: 0.001
  time_period: 1D
  time_range:
  - '2021-03-01'
  - '2021-03-20'
  variable_names:
  - B04
  - B05
input_configs:
- data_id: S2L2A
  open_params:
    tile_size:
    - 1024
    - 1024
  store_id: '@sentinelhub_eu'
output_config:
  data_id: sh-antimeridian_S2L2A_B04_B05.zarr
  replace: true
  store_id: s3
  store_params:
    root: eurodatacube-scratch
```
