### ISSUE TITLE
custom colormaps not working with v0.13.0.dev2

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#746]
**Describe the bug**
When configuring an xcube server with custom color maps, I receive the below traceback:

```
  - Identifier: sentinel_2
    ColorMappings:
      Chlorophyll_mean:
        ColorFile: /xcube/resources/custom_colormaps/chl_DeM2.cpd
        ValueRange: [0., 40.]
```

```
[E 2022-10-07 12:34:07,194 xcube] Internal error: Invalid server configuration:
{'ColorFile': '/xcube/resources/custom_colormaps/Bfg_schweb_50.cpd', 'ValueRange': [0.0, 50.0]} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['Styles']['items']['properties']['ColorMappings']['additionalProperties']:
    {'oneOf': [{'additionalProperties': False,
                'properties': {'ColorBar': {'type': 'string'},
                               'ValueRange': {'items': [{'type': 'number'},
                                                        {'type': 'number'}],
                                              'type': 'array'}},
                'type': 'object'},
               {'additionalProperties': False,
                'properties': {'ColorFile': {'type': 'string'}},
                'required': ['ColorFile'],
                'type': 'object'}]}

On instance['Styles'][0]['ColorMappings']['Turbidity_865_mean']:
    {'ColorFile': '/xcube/resources/custom_colormaps/Bfg_schweb_50.cpd',
     'ValueRange': [0.0, 50.0]}

```

**Comment by AliceBalfanz** [comment]
Closing, this error was due to wrong usage, `ValueRange` must be omitted when using `ColorFile`, the Value Range is specified by the custom colormap
```
  - Identifier: sentinel_2
    ColorMappings:
      Chlorophyll_mean:
        ColorFile: /xcube/resources/custom_colormaps/chl_DeM2.cpd
        ValueRange: [0., 40.]
```
