### ISSUE TITLE
xcube Server fails to resolve datasets for relative parent paths

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#758]
**Describe the bug**

xcube Server can no longer locate local datasets when they identidied by relative paths including parent folders. 

**To Reproduce**

In `examples/server/demo/config.yml` add a datasets entry:

```yaml
Datasets:
  - Identifier: cmems
    Path: ../../../dataset-bal-analysis-forecast-wav-hourly.zarr
    FileSystem: file
    Style: default
```

My current working directory is my xcube sources folder: `D:/Projects/xcube`. Run xcube Server:

    xcube serve --loglevel DEBUG serve -vvvv --traceperf -c examples/serve/demo/config.yml 

   

After GET http://localhost:8080/datasets?details=1, one can find in the logs 

```
...
[I 2022-10-24 15:28:50,438 xcube] Loading details for dataset cmems
[I 2022-10-24 15:28:50,442 xcube] Opened dataset 'cmems' from data store 'file_2': took 4.25ms
[W 2022-10-24 15:28:50,442 xcube] Skipping dataset cmems: could not open dataset: Failed to open dataset 'D:/Projects/xcube/examples/serve/demo/dataset-bal-analysis-forecast-wav-hourly.zarr': group not found at path ''
...
```

**Expected behavior**

Dataset should be opened from `${config-dir}/../../../dataset-bal-analysis-forecast-wav-hourly.zarr`, in the example above namely `D:/Projects/xcube/dataset-bal-analysis-forecast-wav-hourly.zarr`.

**EDIT**

The same happens when specifying an absolute path:

```yaml
Datasets:
  - Identifier: cmems
    Path: D:/Projects/xcube/dataset-bal-analysis-forecast-wav-hourly.zarr
    FileSystem: file
    Style: default
```

It only works if specifying a relative path inside the config directory. After copying the dataset into the configuration directory,  then

```yaml
Datasets:
  - Identifier: cmems
    Path: dataset-bal-analysis-forecast-wav-hourly.zarr
    FileSystem: file
    Style: default
```

works.

**Comment by forman** [comment]
Issue is back for place group paths, e.g., the following still does not work:

```yaml
    Datasets:
      - Identifier: ds1
        Path: openSR_nordfriesland_S2L2A_selected_dates_10m-v4.levels
        Title: Nordfriesland Sentinel-2
        PlaceGroups:
          - PlaceGroupRef: ../dectree/places/aoi/mussel_oyster_beds_examples_Polygon.shp
```
