### ISSUE TITLE
`xcube server` store configuration flexibility for `root` parameter

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#836]
**Is your feature request related to a problem? Please describe.**
For DeepESDL we have user storage in s3 buckets. Each team gets their own bucket which follows the naming convention hub-deepesdl<team-nr>. We want to configure xcube server to also show the cubes stored in the user storage via xcube viewer.

**Describe the solution you'd like**
I would like to be able to specify a value range, which should be used in the root parameter. In case the identifier remaining being a problem, maybe it could be suffixed with the actual root? 
So I would like to configure it e.g. like this: 

```yaml
  - Identifier: team
    StoreId: s3
    StoreParams:
      root: "hub-deepesdl"
      suffix_range: [0-15]
      storage_options:
        anon: false
    Datasets:
      - Path: "*.zarr"
        Style: default
      - Path: "*.levels"
        Style: default
```
Which then would resolve in different stores with root e.g. hub-deepesdl0 or hub-deepesdl15

**Describe alternatives you've considered**
I can manually configure each identifier per team, but this will quickly become a very long list and might be difficult to maintain.
